import json
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import List, Optional
from sqlalchemy.orm import Session

from app.config import settings
from app.models.database import ExportReport, Paper, ProjectPaper, ResearchProject
from app.services.citation_service import CitationService
from app.services.literature_review_service import LiteratureReviewService

logger = logging.getLogger(__name__)


class ExportService:
    """Generates and persists professional academic research reports in PDF, DOCX, MD, JSON, and BibTeX."""

    def __init__(self):
        self.export_dir = Path(settings.export_storage_path)
        self.export_dir.mkdir(parents=True, exist_ok=True)
        self.lit_review_service = LiteratureReviewService()

    def generate_report(
        self,
        db: Session,
        title: str,
        report_type: str,
        format_type: str,
        citation_style: str = "IEEE",
        project_id: Optional[int] = None,
        paper_ids: Optional[List[int]] = None,
    ) -> ExportReport:
        format_clean = format_type.lower().strip()
        timestamp_str = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        safe_title = "".join([c if c.isalnum() else "_" for c in title])[:40]
        filename = f"{safe_title}_{timestamp_str}.{format_clean}"
        file_path = self.export_dir / filename

        # Fetch literature review or structured content
        review = self.lit_review_service.build_literature_review(
            db=db,
            project_id=project_id,
            paper_ids=paper_ids,
            topic=title,
            citation_style=citation_style,
        )

        if format_clean == "pdf":
            self._write_pdf(file_path, review)
        elif format_clean == "docx":
            self._write_docx(file_path, review)
        elif format_clean == "md":
            self._write_markdown(file_path, review)
        elif format_clean == "json":
            self._write_json(file_path, review)
        elif format_clean == "bibtex":
            self._write_bibtex(db, file_path, paper_ids, project_id, citation_style)
        else:
            # Default to Markdown
            self._write_markdown(file_path, review)

        file_size = os.path.getsize(file_path) if file_path.exists() else 0

        report_record = ExportReport(
            title=title,
            report_type=report_type,
            format=format_clean,
            citation_style=citation_style,
            project_id=project_id,
            file_path=str(file_path),
            file_size_bytes=file_size,
            status="completed",
        )
        db.add(report_record)
        db.commit()
        db.refresh(report_record)
        return report_record

    def _write_markdown(self, path: Path, review) -> None:
        lines = [
            f"# {review.title}",
            f"\n*Generated by ResearchOps AI on {datetime.utcnow().strftime('%B %d, %Y')}*\n",
            f"**Citation Style**: {review.citation_style}\n",
            "---\n",
        ]
        for sec_title, sec_content in review.sections.items():
            lines.append(f"## {sec_title}\n\n{sec_content}\n")

        lines.append("## 11. References\n")
        for ref in review.references:
            lines.append(f"- {ref}")

        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

    def _write_json(self, path: Path, review) -> None:
        data = {
            "title": review.title,
            "generated_at": str(review.created_at),
            "citation_style": review.citation_style,
            "sections": review.sections,
            "references": review.references,
        }
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)

    def _write_bibtex(self, db: Session, path: Path, paper_ids, project_id, citation_style) -> None:
        if not paper_ids and project_id:
            papers = (
                db.query(Paper)
                .join(ProjectPaper, ProjectPaper.paper_id == Paper.id)
                .filter(ProjectPaper.project_id == project_id)
                .all()
            )
            paper_ids = [p.id for p in papers]
        elif not paper_ids:
            papers = db.query(Paper).limit(10).all()
            paper_ids = [p.id for p in papers]

        export = CitationService.export_bulk_citations(db, paper_ids, citation_style)
        with open(path, "w", encoding="utf-8") as f:
            f.write(export.bibtex)

    def _write_docx(self, path: Path, review) -> None:
        try:
            import docx
            doc = docx.Document()
            doc.add_heading(review.title, level=0)
            doc.add_paragraph(f"Generated by ResearchOps AI | Style: {review.citation_style} | Date: {datetime.utcnow().strftime('%B %d, %Y')}")
            doc.add_paragraph("---")

            for sec_title, sec_content in review.sections.items():
                doc.add_heading(sec_title, level=1)
                doc.add_paragraph(sec_content)

            doc.add_heading("11. References", level=1)
            for ref in review.references:
                doc.add_paragraph(ref, style="List Bullet")

            doc.save(str(path))
        except Exception as exc:
            logger.warning(f"python-docx error: {exc}. Falling back to markdown format.")
            self._write_markdown(path, review)

    def _write_pdf(self, path: Path, review) -> None:
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
            from reportlab.lib import colors

            doc = SimpleDocTemplate(
                str(path),
                pagesize=letter,
                rightMargin=54,
                leftMargin=54,
                topMargin=54,
                bottomMargin=54,
            )
            styles = getSampleStyleSheet()
            title_style = ParagraphStyle(
                'DocTitle',
                parent=styles['Heading1'],
                fontSize=20,
                leading=24,
                textColor=colors.HexColor('#1e1b4b'),
            )
            h1_style = ParagraphStyle(
                'SectionHeader',
                parent=styles['Heading2'],
                fontSize=13,
                leading=16,
                textColor=colors.HexColor('#4338ca'),
                spaceBefore=12,
                spaceAfter=6,
            )
            body_style = ParagraphStyle(
                'Body',
                parent=styles['Normal'],
                fontSize=10,
                leading=14,
                textColor=colors.HexColor('#1f2937'),
            )

            story = [
                Paragraph(review.title, title_style),
                Spacer(1, 4),
                Paragraph(f"<b>Platform:</b> ResearchOps AI &nbsp;|&nbsp; <b>Style:</b> {review.citation_style} &nbsp;|&nbsp; <b>Date:</b> {datetime.utcnow().strftime('%B %d, %Y')}", body_style),
                Spacer(1, 10),
                HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e5e7eb'), spaceBefore=5, spaceAfter=15),
            ]

            for sec_title, sec_content in review.sections.items():
                story.append(Paragraph(sec_title, h1_style))
                story.append(Paragraph(sec_content, body_style))
                story.append(Spacer(1, 8))

            story.append(Paragraph("11. References", h1_style))
            for ref in review.references:
                story.append(Paragraph(ref, body_style))
                story.append(Spacer(1, 4))

            doc.build(story)
        except Exception as exc:
            logger.warning(f"ReportLab PDF error: {exc}. Falling back to markdown format.")
            self._write_markdown(path, review)
